### PR TITLE
opal_errd: Fix make check on LPAR

### PR DESCRIPTION
**Pull request by seeteena**
'make check' command runs opal_errd tests that are under 'opal_errd/tests/'. 'opal_errd' command is supported on PowerNV platform, but not on PowerVM platform. Make sure that this test passes on LPAR by ensuring that the test picks up platform specific diff result files.

Before applying the patch:
 - FAIL: opal_errd/run_tests

After applying the patch on LPAR:
 - PASS: opal_errd/run_tests

### CODE REVIEW

**Comment by seeteena** [comment]
Tested the changes on Power NV and Power VM platform and works well. 

make check
make  common/tests/spopen lpd/test/ledtool lpd/test/sesdevices diags/test/bh_structs diags/test/hr_structs diags/test/slider_structs diags/test/bh_mk_healthy diags/test/hr_mk_healthy diags/test/slider_mk_healthy diags/test/bh_mk_hot_power diags/test/hr_mk_hot_power diags/test/slider_mk_hot_power diags/test/encl_dump_pg2 diags/test/encl_vpd
make[1]: Entering directory '/home/seeteena/ppc64-diag'
make[1]: 'common/tests/spopen' is up to date.
make[1]: 'lpd/test/ledtool' is up to date.
make[1]: 'lpd/test/sesdevices' is up to date.
make[1]: 'diags/test/bh_structs' is up to date.
make[1]: 'diags/test/hr_structs' is up to date.
make[1]: 'diags/test/slider_structs' is up to date.
make[1]: 'diags/test/bh_mk_healthy' is up to date.
make[1]: 'diags/test/hr_mk_healthy' is up to date.
make[1]: 'diags/test/slider_mk_healthy' is up to date.
make[1]: 'diags/test/bh_mk_hot_power' is up to date.
make[1]: 'diags/test/hr_mk_hot_power' is up to date.
make[1]: 'diags/test/slider_mk_hot_power' is up to date.
make[1]: 'diags/test/encl_dump_pg2' is up to date.
make[1]: 'diags/test/encl_vpd' is up to date.
make[1]: Leaving directory '/home/seeteena/ppc64-diag'
make  check-TESTS
make[1]: Entering directory '/home/seeteena/ppc64-diag'
make[2]: Entering directory '/home/seeteena/ppc64-diag'
PASS: common/run_tests
PASS: diags/test/run_tests
PASS: opal_errd/run_tests
============================================================================
Testsuite summary for ppc64-diag 2.7.9
============================================================================
# TOTAL: 3
# PASS:  3
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
make[2]: Leaving directory '/home/seeteena/ppc64-diag'
make[1]: Leaving directory '/home/seeteena/ppc64-diag'

**Comment by seeteena** [comment]
tested the changed on Power NV and Power VM platform and works well. 
```

make check
Testsuite summary for ppc64-diag 2.7.9
============================================================================
# TOTAL: 3
# PASS:  3
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
```

**Comment by maheshsal** [comment]
So basically all the opal_errd make check that were allowing make check test to verify partial code path would be skipped. Which means make check on other platform will no more verify opal_errd tests. I am bit hesitant to take these changes. Need to see if we can handle this better way.

**Comment by seeteena** [comment]
> So basically all the opal_errd make check that were allowing make check test to verify partial code path would be skipped. Which means make check on other platform will no more verify opal_errd tests. I am bit hesitant to take these changes. Need to see if we can handle this better way.

In powerVM pseries machine, make check fails with following message while running the test "test-opal-elog-parse-000"

```
--- ./opal_errd/../opal_errd/tests-results/test-opal-elog-parse-000.result.pseries.err  2023-05-25 05:23:41.835298945 -0400
+++ /tmp/ppc64-diag-run_tests.stderr.ju1cw7tsP1 2023-05-25 05:23:47.575269405 -0400
@@ -1 +1,2 @@
 opal_errd is not supported on the PowerVM pSeries LPAR platform
+Error accessing directory: /tmp/ppc64-diag-run_tests.out.3tvqBx0nX7/platform
FAIL test-opal-elog-parse-000 with RC undef
FAIL opal_errd/run_tests (exit status: 1)

```
```
cat test-opal-elog-parse-000.result.pseries.err
opal_errd is not supported on the PowerVM pSeries LPAR platform
```

**"Error accessing directory: /tmp/ppc64-diag-run_tests.out.3tvqBx0nX7/platform"** message cannot be added in test-opal-elog-parse-000.result.pseries.err file as it generates unique directory (/tmp/ppc64-diag-run_tests.out.3tvqBx0nX7/platform) for each test run. 

Another possible option is `sed -e ` after the run_binary "./opal-elog-parse/opal-elog-parse and then compare with the result

test-opal-elog-parse-000 test file 

run_binary "./opal-elog-parse/opal-elog-parse" "-l -p $OUT/platform"
**sed -e 's%/tmp/.*/%%;' -i $OUTSTDERR**
diff_with_result

so cat **test-opal-elog-parse-000.result.pseries.err** should be
```

opal_errd is not supported on the PowerVM pSeries LPAR platform
Error accessing directory: platform
```
let me know your thoughts. 
I have seen` test-extract_opal_dump-000` also been handled in similar way

**Comment by maheshsal** [comment]
> let me know your thoughts. I have seen` test-extract_opal_dump-000` also been handled in similar way

Yeah, that also needs to be fixed. 

I think we should make opal_errd to throw unsupported platform error when it tries to run as deamon so that it can not be started as service, however, make check can still pass. What do you think ?

**Comment by seeteena** [comment]
make check is passing with latest changes via https://github.com/power-ras/ppc64-diag/pull/14. 
.

**Comment by seeteena** [comment]
closing this issue as make check is passing now.

**Pull request closed without merging**
