### PR TITLE
ppc64-diag: Perform platform check on opal_errd.c, opal-elog-parse.c, opal-dump-parse.c

### PR DESCRIPTION
**Pull request by barnaliguhathakurata10**
Perform platform check on opal_errd.c, opal-elog-parse.c, opal-dump-parse.c

### CODE REVIEW

**Review by maheshsal — COMMENTED** [review]
opal-dump-parse and opal-elog-parse needs to work on other platform to be able to post-analyze the opal-elogs and SYSDUMP file collected as part of ffdc collection which are saved  to pseries lpar.

**Comment by seeteena** [comment]
> opal-dump-parse and opal-elog-parse needs to work on other platform to be able to post-analyze the opal-elogs and SYSDUMP file collected as part of ffdc collection which are saved to pseries lpar.

Thank you Mahesh for the quick reply. 

https://www.ibm.com/docs/en/linux-on-systems?topic=tools-platform-diagnostics-ppc64-diag

So we will need to update the documentation part in this case. 

The utilities described here are supported in the following Linux® distributions and virtualized environments: 
Support for ppc64-diag utilities

Utility                                    PowerVM® partition on any level of Power® processor

opal-elog-parse                     Not applicable
opal-dump-parse                   Not applicable

Also, same applicable for opal_errd command because we are seeing different error when we ran opal_errd command in PowerVM platform. Can you check https://github.com/power-ras/ppc64-diag/pull/14 ?

**Comment by maheshsal** [comment]
> Thank you Mahesh for the quick reply.
> 
> https://www.ibm.com/docs/en/linux-on-systems?topic=tools-platform-diagnostics-ppc64-diag
> 
> So we will need to update the documentation part in this case.
> 
> The utilities described here are supported in the following Linux® distributions and virtualized environments: Support for ppc64-diag utilities
> 
> Utility PowerVM® partition on any level of Power® processor
> 
> opal-elog-parse Not applicable opal-dump-parse Not applicable

That documentation still holds good. The documentation is about Platform diagnostics on PowerVM where these tools are not applicable. These tools are applicable on lpar only under the context of post-analysis of OPAL platform FFDC data.

**Comment by maheshsal** [comment]
Closing this per previous comment.

**Pull request closed without merging**
